server:
  port: ${SERVER_PORT} #"8080"

spring:
  application:
    name: wallet
  datasource:
    url: ${DB_URL}  #jdbc:postgresql://localhost:5432/wallet_db
    username: ${DB_USER} #root
    password: ${DB_PASSWORD} #root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log      : classpath:/db/changelog/db.changelog-master.yaml
    enabled         : true
    url             : ${DB_URL}
    default-schema  : public
    liquibase-schema: public
    user            : root
    password        : root


